-- rus_build_pack dbazhenov

REPLACE INTO cscart_language_values (`lang_code`, `name`, `value`) VALUES ('ru', 'text_assist_notice', '<p>Для корректной работы платежного модуля  \'Assist\' Вам нужно активировать опцию \"Return to store by returning URL\"  на сайте платежной системы  https://secure.assist.ru/members/  в секции \"Design pages\" .</p>');
REPLACE INTO cscart_language_values (`lang_code`, `name`, `value`) VALUES ('en', 'text_assist_notice', '<p>For successful work of the ''Assist'' payment method, you should activate the "Return to store by returning URL" option at https://secure.assist.ru/members/ in the "Design pages" section on the payment side.</p>');
REPLACE INTO cscart_language_values (`lang_code`, `name`, `value`) VALUES ('bg', 'text_assist_notice', '<p>За да работи правилно платежният метод \'Assist\' трябва да активирате \"Return to store by returning URL\" опцията на  https://secure.assist.ru/members/ в \"Design pages\" секцията на сайта.</p>');
REPLACE INTO cscart_language_values (`lang_code`, `name`, `value`) VALUES ('el', 'text_assist_notice', '<p>Για να πετύχει Assistη μέθοδος πληρωμής, θα πρέπει να ενεργοποιήσετε την \"Return to store by returning URL\"επλογή στη διεύθυνση https: / / secure.assist.ru /members/  στην \"Design pages\"  επιλογή, στην πλευρά πληρωμής. </ p> ');
REPLACE INTO cscart_language_values (`lang_code`, `name`, `value`) VALUES ('no', 'text_assist_notice', '<p>For at \"Assist\" betalingsmåte skal være vellykket bør du aktivere \"Return to store by returning URL\" alternativet på https://secure.assist.ru/members/ i \"Design pages\" seksjonen på betalingssiden.</p>');
REPLACE INTO cscart_language_values (`lang_code`, `name`, `value`) VALUES ('ro', 'text_assist_notice', '<p>Pentru munca de succes a \'Asistentului\' de plată trebuie să activați opțiunea \"Întoarcrea la magazin după URL-ul de întoarcere\", opțiune la https://secure.assist.ru/members/ în secțiunea \"Design pagini\" pe partea de plată.</p>');
REPLACE INTO cscart_language_values (`lang_code`, `name`, `value`) VALUES ('zh', 'text_assist_notice', '<p>\'协助\'付款方式的成功工作,您需要在支付方\"页面设计\"区域https://secure.assist.ru/members/激活\"通过返回URL返回商店\"选项.</p>');

        <item lang="ru" id="text_assist_notice"><![CDATA[<p>Для корректной работы платежного модуля  \'Assist\' Вам нужно активировать опцию "Return to store by returning URL"  на сайте платежной системы  https://secure.assist.ru/members/  в секции \"Design pages\" .</p>]]></item>
        <item lang="en" id="text_assist_notice"><![CDATA[<p>For successful work of the ''Assist'' payment method, you should activate the "Return to store by returning URL" option at https://secure.assist.ru/members/ in the "Design pages" section on the payment side.</p>]]></item>
        <item lang="bg" id="text_assist_notice"><![CDATA[<p>За да работи правилно платежният метод \'Assist\' трябва да активирате \"Return to store by returning URL\" опцията на  https://secure.assist.ru/members/ в \"Design pages\" секцията на сайта.</p>]]></item>
        <item lang="el" id="text_assist_notice"><![CDATA[<p>Για να πετύχει Assistη μέθοδος πληρωμής, θα πρέπει να ενεργοποιήσετε την \"Return to store by returning URL\"επλογή στη διεύθυνση https: / / secure.assist.ru /members/  στην \"Design pages\"  επιλογή, στην πλευρά πληρωμής. </ p> ]]></item>
        <item lang="no" id="text_assist_notice"><![CDATA[<p>For at \"Assist\" betalingsmåte skal være vellykket bør du aktivere \"Return to store by returning URL\" alternativet på https://secure.assist.ru/members/ i \"Design pages\" seksjonen på betalingssiden.</p></item>
        <item lang="ro" id="text_assist_notice"><![CDATA[<p>Pentru munca de succes a \'Asistentului\' de plată trebuie să activați opțiunea \"Întoarcrea la magazin după URL-ul de întoarcere\", opțiune la https://secure.assist.ru/members/ în secțiunea \"Design pagini\" pe partea de plată.</p>]]></item>
        <item lang="zh" id="text_assist_notice"><![CDATA[<p>\'协助\'付款方式的成功工作,您需要在支付方\"页面设计\"区域https://secure.assist.ru/members/激活\"通过返回URL返回商店\"选项.</p>]]></item>